services:
  - type: web
    name: tracker-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn firstproject.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: firstproject.settings
