# Generated by Django 5.2.1 on 2025-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
