# Generated by Django 5.2.1 on 2025-05-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('Studentdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
    ]
