# Generated by Django 5.2.1 on 2025-05-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Studentdata',
        ),
    ]
