# Generated by Django 5.2.1 on 2025-05-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_login_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('productID', models.CharField(max_length=30)),
            ],
        ),
    ]
