# Generated by Django 5.2.1 on 2025-05-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_addproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='file',
        ),
    ]
