# Generated by Django 5.2.1 on 2025-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_studentdata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
