# Generated by Django 5.2.1 on 2025-05-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_colleges_studentdata_collegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
