# Generated by Django 5.2.1 on 2025-05-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_studentdata_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='collegs',
            new_name='colleges_name',
        ),
    ]
