# Generated by Django 5.2.1 on 2025-05-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_collegs_studentdata_colleges_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='colleges_name',
            new_name='college',
        ),
    ]
