# Generated by Django 5.2.1 on 2025-05-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_colleges_name_studentdata_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='college',
            new_name='colleges_name',
        ),
    ]
