# Generated by Django 5.2.1 on 2025-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_college_studentdata_colleges_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
