# Generated by Django 5.2.1 on 2025-06-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_published_data_books_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='total_sales',
            new_name='written',
        ),
    ]
