# Generated by Django 5.2.1 on 2025-06-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
