# Generated by Django 5.2.1 on 2025-06-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_report_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
