# Generated by Django 5.2.1 on 2025-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(max_length=1000)),
            ],
        ),
    ]
