# Generated by Django 5.2.1 on 2025-07-07 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_childs_age_of_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.parents'),
        ),
    ]
