# Generated by Django 5.2.1 on 2025-07-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_childs_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
