# Generated by Django 5.2.1 on 2025-06-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
