# Generated by Django 5.2.1 on 2025-06-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('amount',)},
        ),
    ]
